# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'store_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13store_service.proto\x12\x05store\"O\n\x0eRegressRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\x12\x17\n\x0fpredicted_value\x18\x03 \x01(\x02\"P\n\x0f\x43lassifyRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\x12\x17\n\x0fpredicted_label\x18\x03 \x01(\t\"0\n\x0cSaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x86\x01\n\x0cStoreService\x12\x39\n\x0bSaveRegress\x12\x15.store.RegressRequest\x1a\x13.store.SaveResponse\x12;\n\x0cSaveClassify\x12\x16.store.ClassifyRequest\x1a\x13.store.SaveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGRESSREQUEST']._serialized_start=30
  _globals['_REGRESSREQUEST']._serialized_end=109
  _globals['_CLASSIFYREQUEST']._serialized_start=111
  _globals['_CLASSIFYREQUEST']._serialized_end=191
  _globals['_SAVERESPONSE']._serialized_start=193
  _globals['_SAVERESPONSE']._serialized_end=241
  _globals['_STORESERVICE']._serialized_start=244
  _globals['_STORESERVICE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
